/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2017-12-13 08:26:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/internousdev.00196284658414.005/Desktop/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shop/WEB-INF/lib/struts2-jquery-plugin-3.7.0.jar!/META-INF/struts-jquery-tags.tld", Long.valueOf(1389609360000L));
    _jspx_dependants.put("jar:file:/C:/Users/internousdev.00196284658414.005/Desktop/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shop/WEB-INF/lib/struts2-core-2.3.32.jar!/META-INF/struts-tags.tld", Long.valueOf(1488769580000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.32.jar", Long.valueOf(1492154026000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-jquery-plugin-3.7.0.jar", Long.valueOf(1510714204000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsj_005fhead_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fform_0026_005faction;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsj_005fhead_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fform_0026_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsj_005fhead_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fform_0026_005faction.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("<title>Hello Hello!</title>\r\n");
      if (_jspx_meth_sj_005fhead_005f0(_jspx_page_context))
        return;
      out.write(" <!-- jquerytheme=\"redmond\" ããããã¨ãä¸çºã§ãã¶ã¤ã³ãããããã -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\"/>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\tdiv.container{\r\n");
      out.write("\t\tmax-width:800px;\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\theight: auto;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\tp.box{\r\n");
      out.write("\tborder-bottom: 1px solid lightgray;\r\n");
      out.write("\t}\r\n");
      out.write("\tp.err{\r\n");
      out.write("\t\tcolor:red;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv.result dd{\r\n");
      out.write("\t\tmargin-bottom:32px;\r\n");
      out.write("\t}\r\n");
      out.write("\tfooter.perchase-progress-bar{\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\toverflow: hidden;\r\n");
      out.write("\t\theight: 110px;\r\n");
      out.write("\t\tbackground-color: #f5f5f5;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\toverflow: hidden;\r\n");
      out.write("\t\ttop: 120px;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tfooter.perchase-progress-bar.affix{\r\n");
      out.write("\t\ttop: 0px;\r\n");
      out.write("\t\tposition: fixed;\r\n");
      out.write("\t}\r\n");
      out.write("\tfooter{\r\n");
      out.write("\t\theight: 60px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\tfooter.perchase{\r\n");
      out.write("\t\theight: 120px;\r\n");
      out.write("\t\tbackground-color: #f5f5f5;\r\n");
      out.write("\t\tposition: fixed;\r\n");
      out.write("\t\tbottom: 0;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tborder-top:1px solid #cccccc;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t#wrap{\r\n");
      out.write("\t\tmini-height:100%;\r\n");
      out.write("\t\theight: auto;\r\n");
      out.write("\t\tmargin: auto -0px;\r\n");
      out.write("\t\tpadding: 0 0 0px;\r\n");
      out.write("\t\ttext-shadow:\r\n");
      out.write("\t\t0 0 2px #FFFFFF, 0 0 2px #FFFFFF, 0 0 2px #FFFFFF, 0 0 2px #FFFFFF, 0 0 2px #FFFFFF, 0 0 2px #FFFFFF;/* å½±ãç¡çããæ¿ããã¦ãã */\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t@media(min-width:768px){\r\n");
      out.write("\ttd.td_vertical_align_middle{\r\n");
      out.write("    display:flex;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    }\r\n");
      out.write("\t}/* bootstrap3ã®vertical-align:topãã©ãã«ããã¦æã¡æ¶ãããã®ãã®\r\n");
      out.write("\t\tflexãã¤ããªãè¡ãã¤ãããªãã¨ãé·ããç¶­æã§ããªããã*/\r\n");
      out.write("\r\n");
      out.write("\t.overlay-btn{\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tcolor: #0000FF;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-btn2{\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tcolor: #0000FF;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-btn3{\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tcolor: #0000FF;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-btn4{\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tcolor: #0000FF;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-btn5{\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tcolor: #0000FF;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-btn:hover{\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-btn2:hover{\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-btn3:hover{\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-btn4:hover{\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-btn5:hover{\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t.overlay{\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\twidth:800px;\r\n");
      out.write("\t\theight: 65%;\r\n");
      out.write("\t\tposition: fixed;\r\n");
      out.write("\t\tleft: 2%;\r\n");
      out.write("\t\tright: 2%;\r\n");
      out.write("\t\ttop: 20%;\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t\tz-index: 100;\r\n");
      out.write("\t\tbackground: #FFFFFF;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-storage{\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\twidth:800px;\r\n");
      out.write("\t\theight: 1000px;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 2%;\r\n");
      out.write("\t\tright: 2%;\r\n");
      out.write("\t\ttop: 30%;\r\n");
      out.write("\t\tmargin: 0%;\r\n");
      out.write("\t\tz-index: 100;\r\n");
      out.write("\t\tbackground: #FFFFFF;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-mouse{\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\twidth:800px;\r\n");
      out.write("\t\theight: 720px;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 2%;\r\n");
      out.write("\t\tright: 2%;\r\n");
      out.write("\t\ttop: 60%;\r\n");
      out.write("\t\tmargin: 0%;\r\n");
      out.write("\t\tz-index: 100;\r\n");
      out.write("\t\tbackground: #FFFFFF;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-fruit{\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\twidth:800px;\r\n");
      out.write("\t\theight: 360px;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 2%;\r\n");
      out.write("\t\tright: 2%;\r\n");
      out.write("\t\ttop: 79%;\r\n");
      out.write("\t\tmargin: 0%;\r\n");
      out.write("\t\tz-index: 100;\r\n");
      out.write("\t\tbackground: #FFFFFF;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-flower{\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\twidth:800px;\r\n");
      out.write("\t\theight: 400px;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 2%;\r\n");
      out.write("\t\tright: 2%;\r\n");
      out.write("\t\ttop: 83%;\r\n");
      out.write("\t\tmargin: 0%;\r\n");
      out.write("\t\tz-index: 100;\r\n");
      out.write("\t\tbackground: #FFFFFF;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-shadow{\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t\tposition: fixed;\r\n");
      out.write("\t\tleft: 0%;\r\n");
      out.write("\t\ttop: 0%;\r\n");
      out.write("\t\tz-index: 10;\r\n");
      out.write("\t\tbackground: rgba(0,0,0,0.7);\r\n");
      out.write("\t\toverflow:scroll\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.background-top-white{\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 120px;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 0%;\r\n");
      out.write("\t\toverflow: hidden;\r\n");
      out.write("\t\ttop: 0%;\r\n");
      out.write("\t\tz-index: -5;\r\n");
      out.write("\t\tbackground: white;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.background-gray{\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t\tposition: fixed;\r\n");
      out.write("\t\tleft: 0%;\r\n");
      out.write("\t\ttop: 0;\r\n");
      out.write("\t\tz-index: -10;\r\n");
      out.write("\t\tbackground: #f5f5f5;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-close{\r\n");
      out.write("\t\twidth: 70px;\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tfont-size: 18ex;\r\n");
      out.write("\t\tline-height: 0.5;\r\n");
      out.write("\t}\r\n");
      out.write("\t.overlay-close2{\r\n");
      out.write("\t\twidth: 70px;\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tfont-size: 18ex;\r\n");
      out.write("\t\tline-height: 0.5;\r\n");
      out.write("\t}\r\n");
      out.write("\t.overlay-close3{\r\n");
      out.write("\t\twidth: 70px;\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tfont-size: 18ex;\r\n");
      out.write("\t\tline-height: 0.5;\r\n");
      out.write("\t}\r\n");
      out.write("\t.overlay-close4{\r\n");
      out.write("\t\twidth: 70px;\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tfont-size: 18ex;\r\n");
      out.write("\t\tline-height: 0.5;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-close5{\r\n");
      out.write("\t\twidth: 70px;\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tfont-size: 18ex;\r\n");
      out.write("\t\tline-height: 0.5;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.overlay-text{\r\n");
      out.write("\t\tpadding: 5% 10%;\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t\tline-height: 1.5;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv.inliner{\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tdiv.inliner-right{\r\n");
      out.write("\t\ttext-align: right;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tdiv.hidden{\r\n");
      out.write("\t\tstyle=\"display: none;\"\r\n");
      out.write("\t}\r\n");
      out.write("\tbutton.hidden{\r\n");
      out.write("\t\tstyle=\"display: none;\"\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tul.perchase-bottom.perchase-bottom.perchase-bottom > li{\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#taxQuestion:hover >.mini-overlay{\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t}\r\n");
      out.write("\t#taxQuestion:hover img{\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\tz-index: 150;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#taxQuestion >.mini-overlay{\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\ttop: -100px;\r\n");
      out.write("\t\tleft: -250px;\r\n");
      out.write("\t\twidth: 285px;\r\n");
      out.write("\t\theight: 165px;\r\n");
      out.write("\t\tz-index: 100;\r\n");
      out.write("\t\tpadding: 5px 20px;\r\n");
      out.write("\t\tbox-shadow: 1px 1px 5px #c0c0c0;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#securityCodeQuestion:hover >.mini-overlay{\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t}\r\n");
      out.write("\t#securityCodeQuestion:hover img{\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\tz-index: 150;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t#securityCodeQuestion >.mini-overlay{\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\ttop:200px;\r\n");
      out.write("\t\tleft: 180px;\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\theight: 165px;\r\n");
      out.write("\t\tz-index: 100;\r\n");
      out.write("\t\tpadding: 5px 20px;\r\n");
      out.write("\t\tbox-shadow: 1px 1px 5px #c0c0c0;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tth.recyle{\r\n");
      out.write("\t\tbackground-color: #f5f5f5;\r\n");
      out.write("\t\tborder: 1px solid gray;\r\n");
      out.write("\t\tpadding: 2px 2px 2px 2px;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable.recyle{\r\n");
      out.write("\t\tborder: 1px solid gray;\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\tline-height: 2.0;\r\n");
      out.write("\t\tpadding: 2px 2px 2px 2px;\r\n");
      out.write("\t}\r\n");
      out.write("\ttr.recyle{\r\n");
      out.write("\t\tborder: 1px solid gray;\r\n");
      out.write("\t\tpadding: 2px 2px 2px 2px;\r\n");
      out.write("\t}\r\n");
      out.write("\ttd.recyle{\r\n");
      out.write("\t\tborder: 1px solid gray;\r\n");
      out.write("\t\tpadding: 2px 2px 2px 2px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script  type=\"text/javascript\"  charset=\"utf-8\">\r\n");
      out.write("\t\tfunction Orange(){\r\n");
      out.write("\t\t\tvar nowValue = document.getElementById('test').innerHTML;\r\n");
      out.write("\t\t\tvar addValue = \"<img src='orange.png' alt=''>\";\r\n");
      out.write("\t\t\tdocument.getElementById('test').innerHTML = nowValue + addValue;}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"page-header\">\r\n");
      out.write("\t\t\t<a onClick=\"Orange()\" ><h1>ORange <small> ver 3.12.07</small></h1></a>\r\n");
      out.write("\r\n");
      //  s:form
      org.apache.struts2.views.jsp.ui.FormTag _jspx_th_s_005fform_005f0 = (org.apache.struts2.views.jsp.ui.FormTag) _005fjspx_005ftagPool_005fs_005fform_0026_005faction.get(org.apache.struts2.views.jsp.ui.FormTag.class);
      _jspx_th_s_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fform_005f0.setParent(null);
      // /header.jsp(377,0) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fform_005f0.setAction("UserPageAction");
      int _jspx_eval_s_005fform_005f0 = _jspx_th_s_005fform_005f0.doStartTag();
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_s_005fform_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_s_005fform_005f0.doInitBody();
        }
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t");

			String l = (String) session.getAttribute("loginUserIdShadow");
			session.setAttribute("loginUserIdShadow", l);
			String iD=(String)session.getAttribute("loginUserIdShadow");
			if(iD != null){
			out.println("You are logged in as: <strong>"+iD+"</strong><button class='pull-right btn-link'>Jump to User Page!</button>");}
			else out.println("&nbsp");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_s_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fs_005fform_0026_005faction.reuse(_jspx_th_s_005fform_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fs_005fform_0026_005faction.reuse(_jspx_th_s_005fform_005f0);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sj_005fhead_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sj:head
    com.jgeppert.struts2.jquery.views.jsp.ui.HeadTag _jspx_th_sj_005fhead_005f0 = (com.jgeppert.struts2.jquery.views.jsp.ui.HeadTag) _005fjspx_005ftagPool_005fsj_005fhead_005fnobody.get(com.jgeppert.struts2.jquery.views.jsp.ui.HeadTag.class);
    _jspx_th_sj_005fhead_005f0.setPageContext(_jspx_page_context);
    _jspx_th_sj_005fhead_005f0.setParent(null);
    int _jspx_eval_sj_005fhead_005f0 = _jspx_th_sj_005fhead_005f0.doStartTag();
    if (_jspx_th_sj_005fhead_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsj_005fhead_005fnobody.reuse(_jspx_th_sj_005fhead_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsj_005fhead_005fnobody.reuse(_jspx_th_sj_005fhead_005f0);
    return false;
  }
}
